services:
  votesession-cache:
    container_name: votesession-cache
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - votesession-network

  votesession-database:
    container_name: votesession-database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - votesession-dbdata:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - votesession-network

  votesession-api:
    build:
      dockerfile: Dockerfile
    container_name: votesession-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - votesession-database
      - votesession-cache
    environment:
      - SPRING_PROFILES_ACTIVE=prod
        ## DATABASE CONFIGURATION
      - SPRING_DATASOURCE_URL=jdbc:postgresql://votesession-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=false
      # CONFIGURING CACHE
      - SPRING.DATA.REDIS.HOST=votesession-cache
    command: mvn spring-boot:run
    networks:
      - votesession-network

volumes:
  votesession-dbdata:

networks:
  votesession-network:
    driver: bridge
