CREATE TABLE IF NOT EXISTS t_agendas
(
    id          BIGSERIAL    NOT NULL PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);