name: "DEPLOY INFRA"
on:
  workflow_dispatch:
    inputs:
      is-to-destroy:
        description: "Defina se deseja destruir a infraestrutura"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      is-to-destroy: "${{ inputs.is-to-destroy }}"
      environment: dev
      aws-assume-role-arn: "${{ vars.AWS_ASSUME_ROLE_ARN }}"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "${{ vars.AWS_STATEFILE_S3_BUCKET }}"
      aws-lock-dynamodb-table: "${{ vars.AWS_LOCK_DYNAMODB_TABLE }}"
      database_name: "${{ vars.DATABASE_NAME }}"
      database_password: "${{ vars.DATABASE_PASSWORD }}"
      database_username: "${{ vars.DATABASE_USERNAME }}"
      database_instance_name: "${{ vars.DATABASE_INSTANCE_NAME }}"
      deployer_key_name: "${{ vars.DEPLOYER_KEY_NAME }}"
      server_instance_name: "${{ vars.SERVER_INSTANCE_NAME }}"
